/* Generated by itemis CREATE code generator. */

#ifndef STATECHART_REQUIRED_H_
#define STATECHART_REQUIRED_H_

#include "../src/sc_types.h"
#include "Statechart.h"

#ifdef __cplusplus
extern "C"
{
#endif 

/*! \file
This header defines prototypes for all functions that are required by the state machine implementation.

This state machine makes use of operations declared in the state machines interface or internal scopes. Thus the function prototypes:
- statechart_lCD_Init
- statechart_mPU6050_Init
- statechart_gravity_Range
- statechart_mPU6050_Calibrate
- statechart_mPU6050_Read_Accel
- statechart_calculate_Gravity
- statechart_display_Grvt
- statechart_display_LCD
- statechart_send_Uart
- statechart_rMS
are defined.

These functions will be called during a 'run to completion step' (runCycle) of the statechart. 
There are some constraints that have to be considered for the implementation of these functions:
- make sure that the execution time is as short as possible.
*/
extern void statechart_lCD_Init( Statechart* handle);
extern void statechart_mPU6050_Init( Statechart* handle);
extern void statechart_gravity_Range( Statechart* handle);
extern void statechart_mPU6050_Calibrate( Statechart* handle);
extern void statechart_mPU6050_Read_Accel( Statechart* handle);
extern void statechart_calculate_Gravity( Statechart* handle);
extern void statechart_display_Grvt( Statechart* handle);
extern void statechart_display_LCD( Statechart* handle);
extern void statechart_send_Uart( Statechart* handle);
extern void statechart_rMS( Statechart* handle);





#ifdef __cplusplus
}
#endif 

#endif /* STATECHART_REQUIRED_H_ */
